#!/bin/bash
alias p="chmod +x [head=0-9]*; git add .; git commit -m "commit"; git push"
git config --global user.email tahir.ibrahimov2012@gmail.com
git config --global user.name Tahir1234
alias per="chmod +x"
alias c="clear"
